# Unfortunately, csv file doesn't give us districts names,
# so I had to get them manually from voivodeships' sites

itod = [None,  # indexing starts from 1
        "Wrocław",
        "Jelenia Góra",
        "Legnica",
        "Wałbrzych",
        "Bydgoszcz",
        "Toruń",
        "Włocławek",
        "Lublin",
        "Biała Podlaska",
        "Chełm",
        "Puławy",
        "Zamość",
        "Zielona Góra",
        "Gorzów Wielkopolski",
        "Łódź",
        "Łódź",
        "Piotrków Trybunalski",
        "Sieradz",
        "Skierniewice",
        "Kraków",
        "Kraków",
        "Kraków",
        "Chrzanów",
        "Myślenice",
        "Nowy Sącz",
        "Nowy Targ",
        "Tarnów",
        "Warszawa",
        "Warszawa",
        "Ciechanów",
        "Legionowo",
        "Ostrołęka",
        "Piaseczno",
        "Płock",
        "Radom",
        "Siedlce",
        "Opole",
        "Opole",
        "Rzeszów",
        "Krosno",
        "Przemyśl",
        "Tarnobrzeg",
        "Białystok",
        "Łomża",
        "Suwałki",
        "Gdańsk",
        "Gdańsk",
        "Słupsk",
        "Katowice",
        "Bielsko-Biała",
        "Bytom",
        "Częstochowa",
        "Gliwice",
        "Sosnowiec",
        "Kielce",
        "Kielce",
        "Olsztyn",
        "Elbląg",
        "Ełk",
        "Poznań",
        "Kalisz",
        "Konin",
        "Leszno",
        "Piła",
        "Szczecin",
        "Koszalin",
        "Stargard Szczeciński",
        "Szczecinek"
        ]
